In [1]:
import numpy as np
import scipy
import scipy.linalg

### Задание №1

Решить систему уравнений методом Крамера: 
1. Решить систему уравнений методом Крамера:

a) $\left\{\begin{array}{l}{x_{1}-2 x_{2}=1} \\ {3 x_{1}-4 x_{2}=7}\end{array}\right.$

б) $\left\{\begin{array}{l}{2 x_{1}-x_{2}+5 x_{3}=10} \\ {x_{1}+x_{2}-3 x_{3}=-2} \\ {2 x_{1}+4 x_{2}+x_{3}=1}\end{array}\right.$

Первое уравнение:

In [2]:
a = np.array([[1,-2],[3,-4]])
b = np.array([1,7])

In [3]:
np.linalg.solve(a,b)

array([5., 2.])

Второе уравнение:

In [4]:
a = np.array([[2,-1, 5],[1,1,-3],[2,4,1]])
b = np.array([10,-2,1])

In [5]:
np.linalg.solve(a,b)

array([ 2., -1.,  1.])

### Задание №2

Найти L -матрицу LU -разложения для матрицы коэффициентов:

a) $\left(\begin{array}{ccc}{1} && {2} && {4} \\ {2} && {9} && {12} \\ {3} && {26} && {30}\end{array}\right)$

б) $\left(\begin{array}{cccc}{1} && {1} && {2} && {4} \\ {2} && {5} && {8} && {9} \\ {3} && {18} && {29} && {18} \\ {4} && {22} && {53} && {33}\end{array}\right)$

Первая матрица:

In [6]:
a = np.array([[1,2,4],[2,9,12],[3,26,30]])
a

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

In [7]:
P, L, U = scipy.linalg.lu(a)
L

array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.8       , 1.        ]])

Вторая матрица:

In [8]:
a = np.array([[1,1,2,4],[2,5,8,9],[3,18,29,18],[4,22,53,33]])
a

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

In [9]:
P, L, U = scipy.linalg.lu(a)
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.75      , -0.25      ,  1.        ,  0.        ],
       [ 0.25      ,  0.75      , -0.17073171,  1.        ]])

### Задание №3

Решить систему линейных уравнений методом LU -разложения

$\left\{\begin{array}{l}{2 x_{1}+x_{2}+3 x_{3}=1} \\ {11 x_{1}+7 x_{2}+5 x_{3}=-6} \\ {9 x_{1}+8 x_{2}+4 x_{3}=-5}\end{array}\right.$

In [10]:
a = np.array([[2,1,3],[11,7,5],[9,8,4]])
a

array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])

In [11]:
b = np.array([1,-6,-5])
b

array([ 1, -6, -5])

In [12]:
np.linalg.solve(a,b)

array([-1.,  0.,  1.])

In [13]:
scipy.linalg.lu_solve(scipy.linalg.lu_factor(a),b)

array([-1.,  0.,  1.])

### Задание №4

Решить систему линейных уравнений методом Холецкого

$\left\{\begin{array}{l}{81 x_{1}-45 x_{2}+45 x_{3}=531} \\ {-45 x_{1}+50 x_{2}-15 x_{3}=-460} \\ {45 x_{1}-15 x_{2}+38 x_{3}=193}\end{array}\right.$

In [14]:
a = np.array([[81,-45,45],[-45,50,-15],[45,-15,38]])
a

array([[ 81, -45,  45],
       [-45,  50, -15],
       [ 45, -15,  38]])

In [15]:
b = np.array([531,-460,193])
b

array([ 531, -460,  193])

In [16]:
np.linalg.solve(a,b)

array([ 6., -5., -4.])

In [17]:
scipy.linalg.cho_solve(scipy.linalg.cho_factor(a), b)

array([ 6., -5., -4.])