In [1]:
import numpy as np

### Задание №1

Найти с помощью NumPy SVD для матрицы

$\left(\begin{array}{ccc}{1} & {2} & {0} \\ {0} & {0} & {5} \\ {3} & {-4} & {2} \\ {1} & {6} & {5} \\ {0} & {1} & {0}\end{array}\right)$

In [2]:
A = np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [3]:
np.linalg.svd(A)

(array([[ 0.17056501,  0.15680918, -0.53077508, -0.79905375, -0.16158397],
        [ 0.39287016, -0.52933945,  0.6134793 , -0.43375771,  0.03082495],
        [-0.14366152, -0.82449256, -0.52379105,  0.14049848,  0.07400343],
        [ 0.88843702,  0.06074346, -0.24655277,  0.37755832, -0.06042632],
        [ 0.08125046,  0.10831843, -0.08231425, -0.10524851,  0.98173958]]),
 array([8.82486885, 6.14060608, 2.53271528]),
 array([[ 0.07116451,  0.71702467,  0.69340553],
        [-0.36737824,  0.66514082, -0.65009301],
        [-0.92734505, -0.20847855,  0.31075368]]))

In [4]:
U, S, W = np.linalg.svd(A)

In [5]:
V = W.T

In [6]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = S

In [7]:
D

array([[8.82486885, 0.        , 0.        ],
       [0.        , 6.14060608, 0.        ],
       [0.        , 0.        , 2.53271528],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [8]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.00000000e+00  2.00000000e+00 -1.72084569e-15]
 [-6.66133815e-16  6.66133815e-16  5.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  6.00000000e+00  5.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00  0.00000000e+00]]


### Задание №2

Для матрицы из предыдущего задания найти:
    
а) евклидову норму;

б) норму Фробениуса.

а) евклидова норма

In [9]:
D[0,0]

8.824868854820448

б) норма Фробениуса

In [10]:
np.linalg.norm(A)

11.045361017187261

In [11]:
np.linalg.norm(A, ord='fro')

11.045361017187261

In [12]:
frob_norm = 0
for i in range(np.linalg.matrix_rank(A)):
    frob_norm += S[i]**2
frob_norm = np.sqrt(frob_norm)
frob_norm

11.045361017187265